server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    add_header X-Content-Type-Options nosniff always;

    location ~* \.(map|ts|tsx)$ {
        return 404;
    }

    location ^~ /src/ {
        return 404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml image/svg+xml;
}
